import type { Metadata } from "next";
import {  Geist, Geist_Mono, Koulen, Nunito  } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const koulen = Koulen({
  variable: '--font-koulen',
  weight: '400', // Only 400 available
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en" suppressHydrationWarning>

      <body
        className={`${geistSans.variable} ${koulen.variable} ${geistMono.variable} antialiased`}
       suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
